const CARTILLA_DATA={
  modulos:{giron:{titulo:"I. Girón",icon:"🏛️"},ambiental:{titulo:"II. Proyecto Ambiental",icon:"🌱"},riesgos:{titulo:"III. Riesgos Físicos",icon:"⚠️"},vial:{titulo:"IV. Seguridad Vial",icon:"🚦"},saludable:{titulo:"V. Vida Saludable",icon:"🥗"},emprendimiento:{titulo:"VI. Emprendimiento",icon:"💡"}},
  giron:{
    intro:"Girón, Monumento Nacional de Santander, nos invita a conocer su historia, flora y fauna únicas, leyendas y gastronomía.",
    historia:{fundacion:"15 de enero de 1631",fundador:"Francisco Mantilla de los Ríos",texto:"A impulso de Don Francisco Mantilla de los Ríos fue fundada la ciudad el 15 de enero de 1631. Fue trasladada al sitio Macaregua, donde hoy se encuentra.",postfundacion:"El sector histórico comprende 64 hectáreas con arquitectura colonial del siglo XVII: casas blancas, puertas marrones, balcones amplios y calles empedradas."},
    guanes:"Los guanes habitaron la región antes de la colonización española. Eran conocidos por su organización social, agricultura y resistencia ante la colonia.",
    vocabularioGuane:[{palabra:"Muy hunza",significado:"Buenos días"},{palabra:"Akundun",significado:"Agradecimiento"},{palabra:"Ñakuna",significado:"Adiós"},{palabra:"Yama",significado:"Agua"},{palabra:"Kaká",significado:"Comida"},{palabra:"Manka",significado:"Tierra"},{palabra:"Yage",significado:"Planta sagrada"},{palabra:"Carigua",significado:"Montaña"}],
    lugaresTuristicos:[
      {nombre:"Basílica Menor de San Juan Bautista",desc:"La iglesia más antigua de Girón, ubicada en la plaza principal.",foto:"assets/lugar_basilica.jpg"},
      {nombre:"Capilla Nuestra Señora de las Nieves",desc:"Arquitectura colonial levantada el 15 de mayo de 1757.",foto:"assets/lugar_capilla.jpg"},
      {nombre:"Parroquia Santa Cruz",desc:"Segunda parroquia en antigüedad del municipio.",foto:"assets/lugar_parroquia.jpg"},
      {nombre:"Puentes Coloniales",desc:"Seis puentes coloniales en piedra de lajas: Puente el Moro, San José y las Nieves.",foto:"assets/lugar_puentes.jpg"},
      {nombre:"La Casona",desc:"Restaurante tradicional con gastronomía típica santandereana.",foto:"assets/lugar_casona.jpg"},
      {nombre:"Parque Peralta",desc:"'El de los enamorados', donde se construyó el primer caserío de Girón.",foto:"assets/lugar_peralta.jpg"},
      {nombre:"Parque las Nieves",desc:"Pequeña plaza en damero, sitio predilecto para matrimonios.",foto:"assets/lugar_parque_nieves.jpg"},
      {nombre:"Parque Principal",desc:"Sitio del antiguo mercado dominical colonial.",foto:"assets/lugar_parque_principal.jpg"},
      {nombre:"Parque El Gallineral",desc:"El parque más extenso de la Villa de los Caballeros.",foto:"assets/lugar_gallineral.jpg"},
      {nombre:"El Poblado",desc:"Principal puerta de entrada a Girón con la 'Puerta Grande'.",foto:"assets/lugar_poblado.jpg"},
      {nombre:"Cañón de las Iguanas",desc:"Cascadas y pozos naturales en vereda Chocoa, ideal para deportes extremos.",foto:"assets/lugar_canon.jpg"},
      {nombre:"Mansión del Fraile",desc:"Casa colonial donde nació Eloy Valenzuela, participante de la Expedición Botánica.",foto:"assets/lugar_mansion.jpg"}
    ],
    comidaTipica:[{nombre:"Fritanga gironesa",desc:"Combinación de carnes de cerdo fritas. El Malecón es el sitio más famoso."},{nombre:"Raspados",desc:"Bebida granizada con hielo, esencias y frutas, con casi un siglo de tradición."}],
    leyendas:[{titulo:"La Diosa Oro",texto:"El Río de Oro debe su nombre a una diosa que vivía en sus aguas. La contaminación la hizo huir al océano; regresa en forma de lluvia."},{titulo:"Los pollitos amarillos",texto:"En potreros entre Pantano y Cantalta aparece una gallina con pollitos de oro sobre la tumba de un cacique."},{titulo:"Antón García, el Jinete Sin Cabeza",texto:"Cada cuaresma, un jinete sin cabeza recorre las orillas del Río de Oro cuidando las reliquias de sus antepasados."},{titulo:"Los cotudos",texto:"Historia de habitantes que padecían bocio por consumir sal sin yodo; desapareció con la sal yodada."}],
    rioDeOro:"El Río de Oro fue motor del desarrollo regional. Hoy enfrenta una crisis ecológica por contaminación. Cuidar el río es cuidar la identidad de la región.",
    fauna:[{nombre:"Canario coronado",desc:"Ave popular por su canto y colorido plumaje."},{nombre:"Tortolita rojiza",desc:"Ave pequeña que habita cerca del agua."},{nombre:"Caracol africano",desc:"Especie invasora que compite con especies nativas."},{nombre:"Chulo",desc:"Ave carroñera con agudo sentido del olfato."},{nombre:"Gavilán pollero",desc:"Rapaz adaptada a zonas urbanas y rurales."},{nombre:"Garcita bueyera",desc:"Ave blanca que controla plagas agrícolas."}],
    quiz:[{pregunta:"¿En qué fecha fue fundada la ciudad de Girón?",opciones:["15 de enero de 1631","30 de diciembre de 1638","24 de agosto de 1969","15 de mayo de 1757"],correcta:0},{pregunta:"¿Quién fundó Girón?",opciones:["Sancho Girón","Felipe IV","Francisco Mantilla de los Ríos","Eloy Valenzuela"],correcta:2},{pregunta:"¿Qué pueblo indígena habitó Girón antes de la colonización?",opciones:["Los Muiscas","Los Guanes","Los Wayuu","Los Taironas"],correcta:1},{pregunta:"¿Qué significa la palabra guane 'Yama'?",opciones:["Montaña","Comida","Agua","Tierra"],correcta:2},{pregunta:"Según la leyenda, ¿por qué la Diosa Oro huyó al océano?",opciones:["Se aburrió","La contaminación la enfermó","Los guanes la expulsaron","Por una represa"],correcta:1},{pregunta:"¿Cuántos puentes coloniales conserva Girón?",opciones:["Tres","Cuatro","Seis","Diez"],correcta:2}]
  },
  ambiental:{
    intro:"Este proyecto busca generar conciencia sobre el cuidado del agua, los páramos y los ecosistemas de nuestra región.",
    cartaDel2070:"Una reflexión ficticia narrada por una persona en el año 2070, donde el agua se ha agotado por la contaminación y el cambio climático no atendido a tiempo.",
    paramos:{texto:"Los páramos almacenan agua y la entregan gradualmente a los ríos. Colombia posee la mayor extensión de páramos del mundo.",amenazas:"La ganadería extensiva, cultivos de papa y el cambio climático degradan estos ecosistemas. El 88% no está dentro de áreas protegidas.",datoClave:"El derretimiento de los seis nevados de Colombia es una consecuencia prevista del cambio climático."},
    huellaHidrica:{texto:"La huella hídrica mide el volumen de agua dulce usado para producir bienes y servicios.",datos:["1 kilo de carne de res requiere 16.000 litros de agua.","Una taza de café necesita 140 litros.","La huella hídrica de EE.UU. es de 2.500 m³ por persona al año."]},
    comparendoAmbiental:[{falta:"Consumir goma de mascar",sancion:"Recoger 20 residuos del suelo."},{falta:"Dañar los mobiliarios",sancion:"Reparar el daño económicamente."},{falta:"Desperdicio de agua",sancion:"Trabajo escrito sobre ahorro de agua."},{falta:"Rayar paredes",sancion:"Limpiar y repintar las áreas afectadas."},{falta:"Dañar zonas verdes",sancion:"Reponer y sembrar las plantas."},{falta:"Matoneo y bullying",sancion:"Ruta de atención galanista con remisión a coordinación."}],
    quiz:[{pregunta:"¿Qué función cumplen los páramos?",opciones:["Generan sequías","Son reguladores hídricos","No tienen función","Solo producen oxígeno"],correcta:1},{pregunta:"¿Qué % de páramos colombianos NO está protegido?",opciones:["25%","50%","88%","10%"],correcta:2},{pregunta:"¿Cuántos litros requiere 1 kilo de carne?",opciones:["140","1.600","16.000","160"],correcta:2},{pregunta:"¿Qué sanción aplica por desperdiciar agua?",opciones:["Expulsión","Trabajo escrito sobre ahorro","Ninguna","Multa únicamente"],correcta:1},{pregunta:"¿Principal amenaza para los páramos?",opciones:["Turismo ecológico","Ganadería y cultivos","Reforestación","Fauna silvestre"],correcta:1}]
  },
  riesgos:{
    intro:"Este módulo aborda el dengue transmitido por el Aedes aegypti y la importancia de la mochila de emergencia.",
    aedes:{descripcion:"El Aedes aegypti transmite dengue, zika, chikunguña y fiebre amarilla. Pica al amanecer y al atardecer.",ciclo:["Huevos: en recipientes con agua limpia.","Larvas: nacen en 2-3 días.","Pupas: metamorfosis en 7-10 días.","Adulto: ciclo completo 15 días."],criaderos:"Tanques sin tapa, neumáticos, latas, botellas y canaletas obstruidas.",prevencion:["Evitar agua estancada.","Tapar los tanques.","Usar repelente cada 3 horas.","Limpiar patios frecuentemente."],sintomas:["Fiebre elevada","Dolor de cabeza","Dolor detrás de los ojos","Náuseas","Sarpullido","Cansancio"],tratamiento:["Ir a un centro de salud.","Solo medicamentos recetados.","Usar repelente.","Cubrir la piel."]},
    mochilaEmergencia:["Linterna con pilas.","Radio sin internet.","Agua envasada.","Alimentos no perecederos.","Ropa abrigadora.","Silbato para pedir ayuda.","Fotocopias de documentos.","Medicinas necesarias."],
    quiz:[{pregunta:"¿Qué enfermedades transmite el Aedes aegypti?",opciones:["Solo el dengue","Dengue, zika, chikunguña y fiebre amarilla","Malaria y tifoidea","Ninguna"],correcta:1},{pregunta:"¿Dónde deposita sus huevos?",opciones:["En el aire","En tierra seca","En recipientes con agua limpia","En hojas"],correcta:2},{pregunta:"¿Cuánto dura el ciclo completo?",opciones:["1 día","15 días","6 meses","1 año"],correcta:1},{pregunta:"¿Cuál NO es síntoma del dengue?",opciones:["Fiebre elevada","Dolor detrás de los ojos","Crecimiento del cabello","Dolor muscular"],correcta:2},{pregunta:"¿Qué elemento es esencial para informarse en emergencias?",opciones:["Una tablet","Un radio sin internet","Un teléfono inteligente","Una computadora"],correcta:1}]
  },
  vial:{
    intro:"La seguridad vial es responsabilidad de todos. Respetar las señales protege la vida de peatones, ciclistas y conductores.",
    riesgoColgarse:"Cogerse de la parte trasera de un vehículo puede causar fracturas, traumatismos craneales y la muerte.",
    senalesTransito:[{tipo:"Preventivas",color:"Amarillas",funcion:"Advierten sobre un peligro más adelante."},{tipo:"Reglamentarias",color:"Blancas con borde rojo",funcion:"Indican restricción u obligación."},{tipo:"Informativas",color:"Azules o verdes",funcion:"Brindan información sobre rutas y servicios."}],
    preguntasReflexion:["¿Qué medidas mejorarían la seguridad vial en el colegio?","¿Cómo debes comportarte caminando con amigos?","¿Cómo puedes contribuir a un entorno vial más seguro?"],
    quiz:[{pregunta:"¿Qué riesgo conlleva colgarse de un vehículo?",opciones:["Ninguno","Fracturas y riesgo de muerte","Solo cansancio","Mareo leve"],correcta:1},{pregunta:"¿De qué color son las señales preventivas?",opciones:["Azules","Verdes","Amarillas","Rojas"],correcta:2},{pregunta:"¿Qué tipo de señal indica una restricción?",opciones:["Informativa","Reglamentaria","Preventiva","Decorativa"],correcta:1},{pregunta:"¿Cuál es el comportamiento más seguro al caminar en grupo?",opciones:["Mirar el celular","Caminar atentos respetando señales","Correr entre los carros","Ocupar toda la calzada"],correcta:1}]
  },
  saludable:{
    intro:"Este módulo invita a reflexionar sobre la convivencia sana, el respeto a la diferencia y la prevención de la violencia.",
    tiposViolencia:[{tipo:"Interpersonal",desc:"Uso de fuerza física, verbal o psicológica entre personas."},{tipo:"Ciberviolencia",desc:"Uso de redes sociales para ridiculizar o acosar a alguien."},{tipo:"Psicológica",desc:"Negligencia, insultos, humillaciones y marginación."},{tipo:"De género",desc:"Violencia basada en el sexo o género de la persona."},{tipo:"Cultural",desc:"Impuesta por una cultura que excluye a otros."},{tipo:"Económica",desc:"Falta de consentimiento económico que puede anular contratos."}],
    violentometro:{creador:"Martha Alicia Tronco Rosas, IPN de México.",descripcion:"Herramienta gráfica que clasifica las manifestaciones de violencia en una escala de colores.",fases:["Acumulación de tensión","Explosión / agresión","Arrepentimiento","Reconciliación"]},
    dilemas:[{nombre:"Dilema de Tomás",texto:"Tomás tiene prejuicios sobre una familia gitana basados en estereotipos sin conocerlos.",pregunta:"¿Cómo solucionarías el asunto sin dejarte llevar por prejuicios?"},{nombre:"Dilema de Teresa",texto:"Teresa duda cómo tratar a un compañero por su orientación sexual.",pregunta:"¿Es justificable cambiar el trato hacia un amigo por su orientación?"}],
    quiz:[{pregunta:"¿Qué es la ciberviolencia?",opciones:["Un deporte extremo","Uso de internet para ridiculizar o acosar","Una enfermedad viral","Un videojuego"],correcta:1},{pregunta:"¿Quién diseñó el Violentómetro?",opciones:["Pierre Bourdieu","Max Weber","Martha Alicia Tronco Rosas","Johan Galtung"],correcta:2},{pregunta:"¿Cuál NO es una fase del ciclo de violencia?",opciones:["Acumulación de tensión","Explosión","Celebración pública","Reconciliación"],correcta:2},{pregunta:"La violencia psicológica incluye:",opciones:["Solo golpes","Humillaciones y marginación","Solo accidentes","Solo violencia política"],correcta:1},{pregunta:"¿A qué tipo pertenecen sismos e inundaciones?",opciones:["Violencia natural","Cultural","Económica","Religiosa"],correcta:0}]
  },
  emprendimiento:{
    intro:"El Colegio se rige por la Ley 1014 de 2006, de Fomento a la Cultura del Emprendimiento.",
    objetivosLey:["Fomentar la Cultura del Emprendimiento en todos los niveles educativos.","Apoyar la Creación de Empresas facilitando trámites.","Promover la Innovación y la creatividad.","Desarrollar Competencias en gestión empresarial."],
    feriaEmpresarial:"Entre 2012 y 2015 se realizaron 4 ferias empresariales lideradas por el rector Orlando Becerra Gamboa y docentes de la institución.",
    proyectosDestacados:["Programación robótica","Jabón líquido y crema para manos","Talco para pies","Pizza tropical","Chocolates Gran Family","Avena Special Oat","Manillas hipster","Suavizante de tela"],
    ideasEmprendimientoEscolar:["Venta de dulces","Productos de aseo","Artesanías","Reciclaje","Tutorías entre estudiantes"],
    quiz:[{pregunta:"¿Qué ley fomenta el emprendimiento en colegios?",opciones:["Ley 100 de 1993","Ley 1014 de 2006","Ley 115 de 1994","Ley 1620 de 2013"],correcta:1},{pregunta:"¿Cuántas ferias empresariales hubo entre 2012 y 2015?",opciones:["2","3","4","6"],correcta:2},{pregunta:"¿Cuál NO es una idea de emprendimiento escolar?",opciones:["Venta de dulces","Reciclaje","Tutorías","Exportación de maquinaria pesada"],correcta:3}]
  }
};
